### ISSUE TITLE
Firestore Operations List error

### ISSUE THREAD

**Issue by Lizzardd** [Zenika/alpine-firestore-backup#3]
I am getting an error when hitting the list page
exec error: exit status 1

extract from the logs
2019-08-20 13:21:49.832 SASTERROR: (gcloud.beta.firestore.operations.list) PERMISSION_DENIED: The caller does not have permission

IAM Roles
firebase-backup@xxxxxx.gserviceacc... firebase-backup 
Cloud Datastore Import Export Admin
Cloud Datastore Owner
Owner
Storage Admin

The project is using Blaze Plan

**Comment by jlandure** [comment]
Hi @Lizzardd 👋 

Thanks for your feedback. 👍 
Can you share the sha256 of the used image in the `Cloud Run` service? 

<img width="573" alt="Capture d’écran 2019-08-20 à 15 10 00" src="https://user-images.githubusercontent.com/525974/63349895-aa1dd480-c35c-11e9-97b6-9da9433c5bd0.png">

For example, I've checked the behavior of the following image:
`gcr.io/zenika-hub/alpine-firestore-backup@sha256:a87c08e5d54b5a347134e0af7f1360dcb80f688eba41be6aad9818294c353345`

And can you [list the APIs](https://console.cloud.google.com/apis/dashboard) enabled in your project?
I think you have to enable the following APIs:
 * [Firestore API](https://console.cloud.google.com/apis/api/firestore.googleapis.com/overview)
 * [Google Cloud APIs](https://console.cloud.google.com/apis/api/cloudapis.googleapis.com/overview)
 * [Cloud Storage JSON API](https://console.cloud.google.com/apis/api/storage-api.googleapis.com/overview)

Thanks for investigating! 
Please answer if you find a solution to share the solution to the community. 🙌

**Comment by Lizzardd** [comment]
gcr.io/zenika-hub/alpine-firestore-backup@sha256:a87c08e5d54b5a347134e0af7f1360dcb80f688eba41be6aad9818294c353345

**Comment by jlandure** [comment]
Hi @Lizzardd 👋 

Thanks for the details.
For your information, I have less APIs enabled. All the APIs used in the project are listed as enabled in your project.
I have no idea where the problem come from...

Have you seen that I've accepted a PR #2 from a user to change `$GCLOUD_PROJECT_NAME` in `$GCLOUD_PROJECT_ID`? see [README for usage](https://github.com/Zenika/alpine-firestore-backup).

I have just edited the article on dev.to to indicate that.

**Comment by Lizzardd** [comment]
> Hi @Lizzardd 👋
> 
> Thanks for the details.
> For your information, I have less APIs enabled. All the APIs used in the project are listed as enabled in your project.
> I have no idea where the problem come from...
> 
> Have you seen that I've accepted a PR #2 from a user to change `$GCLOUD_PROJECT_NAME` in `$GCLOUD_PROJECT_ID`? see [README for usage](https://github.com/Zenika/alpine-firestore-backup).
> 
> I have just edited the article on dev.to to indicate that.

That seems to have done it. Didn't see that originally, changing to GCLOUD_PROJECT_ID seems to have fixed the problem

**Comment by jlandure** [comment]
Hey @Lizzardd 👋 
I'm glad you've set it up. 🙌 
Sorry for the delay to find how to fix your problem.
Have a great experience with Firestore! 👍
